name: GoogleTests_template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Create build folder inside library folder
      run: cd /home/runner/work/confReader/confReader && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Create build folder inside tests folder
      run: cd /home/runner/work/confReader/confReader/tests && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Make library confReader
      run: cd /home/runner/work/confReader/confReader && cd build && make
    - name: Make tests with CMakeLists
      run: cd /home/runner/work/confReader/confReader/tests && cd build && make
    - name: Run Tests
      run: /home/runner/work/confReader/confReader/tests/build/test_module
